Replace Unicode character with ASCII
Replace Unicode colon with an ASCII colon in informational string
written to stdout. When running with a terminal that doesn't support
UTF-8 encoding, this fixes errors like:

    UnicodeEncodeError: 'ascii' codec can't encode character '\uff1a' in
    position 19: ordinal not in range(128)